/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttrPopup: typeof import('./src/components/AttrPopup.vue')['default']
    GoodItem: typeof import('./src/components/GoodItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopItem: typeof import('./src/components/ShopItem.vue')['default']
    ShopMenu: typeof import('./src/components/ShopMenu.vue')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TSideBar: typeof import('tdesign-mobile-vue')['SideBar']
    TSideBarItem: typeof import('tdesign-mobile-vue')['SideBarItem']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
  }
}
